module.exports = {
  // MISC
  FIREBASE: "https://tradersquare-ed7bc.firebaseio.com",

  // AUTH ACTIONS
  ATTEMPTING_LOGIN: "ATTEMPING_LOGIN",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT: "LOGOUT",

  // AUTH STATES
  LOGGED_IN: "LOGGED_IN",
  ANONYMOUS: "ANONYMOUS",
  AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE"
};
