module.exports = {
  // MISC
  FIREBASE: "https://tradersquare-ed7bc.firebaseio.com",

  // UI FEEDBACK ACTIONS
  DISPLAY_ERROR: "DISPLAY_ERROR",
  DISPLAY_MESSAGE: "DISPLAY_MESSAGE",
  DISMISS_FEEDBACK: "DISMISS_FEEDBACK",

  // AUTH ACTIONS
  ATTEMPTING_LOGIN: "ATTEMPING_LOGIN",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT: "LOGOUT",

  // AUTH STATES
  LOGGED_IN: "LOGGED_IN",
  ANONYMOUS: "ANONYMOUS",
  AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE"
};
